name: cyberWaifuV2
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - cyrus-sasl=2.1.28
  - eigen=3.4.0
  - expat=2.7.1
  - ffmpeg=4.2.2
  - fontconfig=2.14.1
  - freetype=2.13.3
  - gettext=0.21.0
  - glib=2.84.2
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=73.1
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lerc=4.0.0
  - libabseil=20240116.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.12.1
  - libcxx=17.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.20
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openh264=1.8.0
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pcre2=10.42
  - pip=23.3.1
  - pixman=0.40.0
  - python=3.12.1
  - qt-main=5.15.2
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - wheel=0.41.2
  - x264=1!152.20180806
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argparse==1.4.0
      - asgiref==3.9.1
      - attrs==25.3.0
      - av==15.0.0
      - beautifulsoup4==4.13.4
      - bidict==0.23.1
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - click==8.2.1
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dnspython==2.7.0
      - emoji==2.14.1
      - eventlet==0.40.1
      - filelock==3.18.0
      - filetype==1.2.0
      - flask==3.1.1
      - flask-cors==6.0.1
      - flask-socketio==5.5.1
      - flatbuffers==25.2.10
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.176.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - google-genai==1.25.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.3
      - grpcio==1.73.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.33.3
      - humanfriendly==10.0
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.8
      - langchain-core==0.3.68
      - langchain-google-genai==2.0.10
      - langsmith==0.4.5
      - livekit==1.0.11
      - livekit-api==1.0.3
      - livekit-protocol==1.0.4
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - mss==10.0.0
      - multidict==6.6.3
      - nest-asyncio==1.6.0
      - networkx==3.5
      - noisereduce==3.0.3
      - numba==0.61.2
      - numpy==1.26.3
      - oauthlib==3.3.1
      - onnxruntime==1.22.1
      - openai-whisper==20250625
      - orjson==3.10.18
      - packaging==24.2
      - pillow==11.3.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyjwt==2.10.1
      - pynput==1.8.1
      - pyobjc-core==11.1
      - pyobjc-framework-applicationservices==11.1
      - pyobjc-framework-cocoa==11.1
      - pyobjc-framework-coretext==11.1
      - pyobjc-framework-quartz==11.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-engineio==4.12.2
      - python-socketio==5.13.0
      - python-socks==2.7.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scipy==1.16.0
      - simple-websocket==1.1.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - sympy==1.14.0
      - tenacity==8.5.0
      - tiktoken==0.9.0
      - tokenizers==0.21.2
      - torch==2.7.1
      - torchaudio==2.7.1
      - tqdm==4.67.1
      - transformers==4.53.1
      - types-protobuf==6.30.2.20250703
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - webrtcvad==2.0.10
      - websockets==15.0.1
      - websockets-proxy==0.1.3
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - yarl==1.20.1
      - zstandard==0.23.0