name: cyberWaifuV2
channels:
  - defaults
dependencies:
  - ca-certificates=2023.12.12
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.12.1
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - aiofiles==0.7.0
      - aiohttp==3.9.3
      - aioice==0.9.0
      - aiortc==1.9.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==3.7.1
      - argparse==1.4.0
      - asgiref==3.8.1
      - attrs==23.2.0
      - audioread==3.0.1
      - av==14.0.1
      - beautifulsoup4==4.13.4
      - bidict==0.23.1
      - blinker==1.9.0
      - cachetools==5.3.2
      - certifi==2024.8.30
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudflare==2.19.4
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cryptography==42.0.8
      - cycler==0.12.1
      - data-process==0.3.9
      - dataclasses-json==0.6.4
      - decorator==5.1.1
      - dnspython==2.6.1
      - emoji==2.14.1
      - eventlet==0.36.1
      - filelock==3.13.3
      - filetype==1.2.0
      - flask==3.1.0
      - flask-cors==5.0.0
      - flask-socketio==5.3.6
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gevent==24.2.1
      - gevent-websocket==0.10.1
      - google-ai-generativelanguage==0.6.6
      - google-api-core==2.24.0
      - google-api-python-client==2.126.0
      - google-auth==2.28.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-crc32c==1.5.0
      - google-genai==0.3.0
      - google-generativeai==0.7.2
      - googleapis-common-protos==1.66.0
      - greenlet==3.0.3
      - grpcio==1.60.1
      - grpcio-status==1.60.1
      - h11==0.12.0
      - httpcore==0.13.7
      - httplib2==0.22.0
      - httpx==0.18.2
      - huggingface-hub==0.27.1
      - humanfriendly==10.0
      - idna==3.6
      - ifaddr==0.2.0
      - itsdangerous==2.2.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kiwisolver==1.4.5
      - langchain-community==0.0.34
      - langchain-core==0.2.38
      - langchain-google-genai==1.0.10
      - langchain-text-splitters==0.0.1
      - langsmith==0.1.99
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - livekit==0.18.3
      - livekit-api==0.8.1
      - livekit-protocol==0.8.0
      - llvmlite==0.42.0
      - markupsafe==2.1.5
      - marshmallow==3.20.2
      - matplotlib==3.9.0
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - noisereduce==3.0.3
      - numba==0.59.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - onnxruntime==1.20.1
      - openai-whisper==20240930
      - opencv-python==4.10.0.82
      - orjson==3.10.1
      - packaging==23.2
      - pillow==11.1.0
      - platformdirs==4.2.2
      - pooch==1.8.2
      - proto-plus==1.25.0
      - protobuf==4.25.5
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.22
      - pycrontab==0.1.2
      - pydantic==2.10.0
      - pydantic-core==2.27.0
      - pydotenvs==0.2.0
      - pyee==11.1.0
      - pyjwt==2.8.0
      - pylibsrtp==0.10.0
      - pyopenssl==24.1.0
      - pyparsing==3.1.2
      - python-crontab==3.2.0
      - python-dateutil==2.9.0.post0
      - python-engineio==4.9.1
      - python-socketio==5.11.2
      - python-socks==2.5.3
      - pyyaml==6.0.2
      - regex==2023.12.25
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3986==1.5.0
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - simple-websocket==1.0.0
      - six==1.16.0
      - sniffio==1.3.0
      - soundfile==0.12.1
      - soupsieve==2.7
      - soxr==0.3.7
      - sqlalchemy==2.0.27
      - starlette==0.37.1
      - sympy==1.13.1
      - tenacity==8.2.3
      - threadpoolctl==3.5.0
      - tiktoken==0.6.0
      - tokenizers==0.21.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - tqdm==4.66.2
      - transformers==4.48.1
      - triton==3.1.0
      - types-protobuf==4.25.0.20240417
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - uritemplate==4.1.1
      - urllib3==2.2.0
      - webrtcvad==2.0.10
      - websockets==13.0
      - websockets-proxy==0.1.3
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - yarl==1.9.4
      - zope-event==5.0
      - zope-interface==6.4.post2
      - zstandard==0.23.0